# fly.toml app configuration file generated for homework-search-frosty-frog-6982 on 2024-01-28T22:36:52+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'homework-search-frosty-frog-6982'
primary_region = 'otp'

[build]

[http_service]
  internal_port = 2222
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
